package ejercicios.managementstudio;

import ejercicios.dto.Usuari;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author laura
 */
public class MainFrame extends javax.swing.JFrame {

    Login login;
    SecondMain secondMain;
    ViewExercises viewExer;
    ModExer modExer;
    AddExer addExer;
    DelExer delExer;
    CreateWorkout createWorkout;
    AddUser addUser;
    ModUser modUser;
    DelUser delUser;
    About about;

    public MainFrame() {
        initComponents();
        setSize(700, 500);
        setLocationRelativeTo(null);
        add(mainPanel, BorderLayout.CENTER);
        menuBar.setVisible(false);
        mainPanel.revalidate();
        mainPanel.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenu();
        menuAddUser = new javax.swing.JMenuItem();
        menuModUser = new javax.swing.JMenuItem();
        menuDelUser = new javax.swing.JMenuItem();
        menuExercises = new javax.swing.JMenu();
        menuViewExer = new javax.swing.JMenuItem();
        menuModExer = new javax.swing.JMenuItem();
        menuAddExer = new javax.swing.JMenuItem();
        menuDelExer = new javax.swing.JMenuItem();
        menuWorkout = new javax.swing.JMenu();
        menuCreateWorkout = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManagementStudio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        getContentPane().setLayout(null);

        mainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mainPanel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar sesión");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("www.ManagementStudio.com");

        btnLogin.setBackground(new java.awt.Color(102, 0, 102));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imglog.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenlogin.png"))); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(493, 493, 493))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(282, 282, 282))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(281, 281, 281))
        );

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 570, 580);

        menuFile.setText("File");

        menuSignOut.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuSignOut.setText("Sign out");
        menuSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignOutActionPerformed(evt);
            }
        });
        menuFile.add(menuSignOut);

        menuExit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuUsers.setText("Users");

        menuAddUser.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuAddUser.setText("Add user");
        menuAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddUserActionPerformed(evt);
            }
        });
        menuUsers.add(menuAddUser);

        menuModUser.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuModUser.setText("Modify user");
        menuModUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModUserActionPerformed(evt);
            }
        });
        menuUsers.add(menuModUser);

        menuDelUser.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuDelUser.setText("Delete user");
        menuDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelUserActionPerformed(evt);
            }
        });
        menuUsers.add(menuDelUser);

        menuBar.add(menuUsers);

        menuExercises.setText("Exercises");

        menuViewExer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuViewExer.setText("View exercises");
        menuViewExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewExerActionPerformed(evt);
            }
        });
        menuExercises.add(menuViewExer);

        menuModExer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuModExer.setText("Modify exercise");
        menuModExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModExerActionPerformed(evt);
            }
        });
        menuExercises.add(menuModExer);

        menuAddExer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuAddExer.setText("Add exercise");
        menuAddExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddExerActionPerformed(evt);
            }
        });
        menuExercises.add(menuAddExer);

        menuDelExer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuDelExer.setText("Delete exercise");
        menuDelExer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelExerActionPerformed(evt);
            }
        });
        menuExercises.add(menuDelExer);

        menuBar.add(menuExercises);

        menuWorkout.setText("Workouts");

        menuCreateWorkout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuCreateWorkout.setText("Create Workout");
        menuCreateWorkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateWorkoutActionPerformed(evt);
            }
        });
        menuWorkout.add(menuCreateWorkout);

        menuBar.add(menuWorkout);

        menuHelp.setText("Help");

        menuAbout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddUserActionPerformed
        addUser = new AddUser(this, true);
        addUser.setVisible(true);
        secondMain.pintarUsers();
        secondMain.revalidate();
        secondMain.repaint();
    }//GEN-LAST:event_menuAddUserActionPerformed


    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuViewExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewExerActionPerformed
        viewExer = new ViewExercises(this, true);
        viewExer.setVisible(true);
        secondMain.revalidate();
        secondMain.repaint();
    }//GEN-LAST:event_menuViewExerActionPerformed

    private void menuModExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModExerActionPerformed
        modExer = new ModExer(this, true);
        modExer.setVisible(true);
        getContentPane().revalidate();
        getContentPane().repaint();
    }//GEN-LAST:event_menuModExerActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        about = new About(this, true);
        about.setVisible(true);
        getContentPane().revalidate();
        getContentPane().repaint();
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignOutActionPerformed
        secondMain.setVisible(false);
        mainPanel.setVisible(true);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_menuSignOutActionPerformed

    private void menuAddExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddExerActionPerformed
        addExer = new AddExer(this, true);
        addExer.setVisible(true);
        getContentPane().revalidate();
        getContentPane().repaint();
    }//GEN-LAST:event_menuAddExerActionPerformed

    private void menuModUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModUserActionPerformed
        modUser = new ModUser(this, true);
        modUser.setVisible(true);
        secondMain.pintarUsers();
        secondMain.revalidate();
        secondMain.repaint();
    }//GEN-LAST:event_menuModUserActionPerformed

    private void menuDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelUserActionPerformed
        delUser = new DelUser(this, true);
        delUser.setVisible(true);
        secondMain.pintarUsers();
        secondMain.revalidate();
        secondMain.repaint();
    }//GEN-LAST:event_menuDelUserActionPerformed

    private void menuDelExerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelExerActionPerformed
        delExer = new DelExer(this, true);
        delExer.setVisible(true);
        getContentPane().revalidate();
        getContentPane().repaint();
    }//GEN-LAST:event_menuDelExerActionPerformed

    private void menuCreateWorkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateWorkoutActionPerformed
        createWorkout = new CreateWorkout(this, true);
        createWorkout.setVisible(true);
        getContentPane().revalidate();
        getContentPane().repaint();
    }//GEN-LAST:event_menuCreateWorkoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login = new Login(this, true);
        login.setVisible(true);

        if (login.isAuthenticated()) {
            showSecondMain(login.userConnected);
            getContentPane().revalidate();
            getContentPane().repaint();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /*
    Method to change the main view when someone is logged in the app
     */
    private void showSecondMain(Usuari userConnected) {
        secondMain = new SecondMain(userConnected);
        mainPanel.setVisible(false);
        getContentPane().add(secondMain);
        secondMain.setBounds(0, 0, 700, 500);
        secondMain.setVisible(true);
        menuBar.setVisible(true);
        if (!userConnected.isInstructor()) {
            menuUsers.setVisible(false);
            menuAddExer.setVisible(false);
            menuModExer.setVisible(false);
            menuDelExer.setVisible(false);
            menuCreateWorkout.setVisible(false);
        }
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Color color = new Color(19,13,129);
        UIManager.put("nimbusBase", color);
        color = new Color(62,62,68);
        UIManager.put("control", color);
        UIManager.put("text", Color.white);
        color = new Color(62,62,68);
        UIManager.put("nimbusLightBackground", Color.DARK_GRAY);
        UIManager.put("info", Color.CYAN);
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuAddExer;
    private javax.swing.JMenuItem menuAddUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCreateWorkout;
    private javax.swing.JMenuItem menuDelExer;
    private javax.swing.JMenuItem menuDelUser;
    private javax.swing.JMenu menuExercises;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuModExer;
    private javax.swing.JMenuItem menuModUser;
    private javax.swing.JMenuItem menuSignOut;
    private javax.swing.JMenu menuUsers;
    private javax.swing.JMenuItem menuViewExer;
    private javax.swing.JMenu menuWorkout;
    // End of variables declaration//GEN-END:variables
}
