
package ejercicios.managementstudio;

import ejercicios.DataAcces.DataAccess;
import ejercicios.dto.Exercici;
import ejercicios.dto.Usuari;
import ejercicios.dto.Workout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author laura
 */
public class SecondMain extends javax.swing.JPanel {

    /**
     * Creates new form SecondMain
     */
    private javax.swing.JList<Usuari> lstUsers;
    private javax.swing.JList<Exercici> lstWorkoutDetail;
    private javax.swing.JComboBox<Workout> cmbWorkout;

    private DataAccess da = new DataAccess();
    private Usuari userConnected = new Usuari();

    public SecondMain(Usuari userConnected) {
        initComponents();       
        this.userConnected = userConnected;
        lstUsers = new javax.swing.JList<>();
        jScrollPane3.setViewportView(lstUsers);
        pintarUsers();
        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });

        cmbWorkout = new JComboBox<>();
        jScrollPane4.setViewportView(cmbWorkout);
        cmbWorkout.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
            cmbWorkoutsValueChanged(evt);
            }
        });
           
        lstWorkoutDetail = new javax.swing.JList<>();
        jScrollPane1.setViewportView(lstWorkoutDetail);
}

    public void pintarUsers() {
        ArrayList<Usuari> users = da.getAllUsersByInstructor(userConnected.getId());
        DefaultListModel<Usuari> dfmu = new DefaultListModel<>();
        dfmu.clear();
        for (Usuari u : users) {
            dfmu.addElement(u);
        }
        lstUsers.setModel(dfmu);
    }

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {
        Usuari userSelected = lstUsers.getSelectedValue();
        pintarWorkouts(userSelected);
    }

    public void pintarWorkouts(Usuari user) {
        ArrayList<Workout> workouts = da.getWorkoutsPerUser(user);
        DefaultComboBoxModel<Workout> dfmw = new DefaultComboBoxModel<>();
        for (Workout w : workouts) {
            dfmw.addElement(w);
        }
        cmbWorkout.setModel(dfmw);
    }

    private void cmbWorkoutsValueChanged(java.awt.event.ActionEvent evt) {
        Workout workout = (Workout)cmbWorkout.getSelectedItem();

    ArrayList<Exercici> exercicis = da.getExercicisPerWorkout(workout);
        DefaultListModel<Exercici> dfme = new DefaultListModel<>();
        for (Exercici e : exercicis) {
            dfme.addElement(e);
        }
        lstWorkoutDetail.setModel(dfme);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();

        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setText("Users:");

        jLabel2.setText("Workouts:");

        jLabel3.setText("Workout details:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 390, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
