/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicios.managementstudio;

import java.util.ArrayList;
import net.calendar.ActiveButtonListener;
import net.calendar.Workout;

public class WorkoutCalendar extends javax.swing.JFrame {

    
    ArrayList<Workout> workouts = new ArrayList<>();
    
    public WorkoutCalendar() {
        initComponents();
        Workout workout1 = new Workout(1, "2024-12-16", 100, "Comentario 1", 3);
        Workout workout2 = new Workout(2, "2024-12-18", 101, "Comentario 2", 6);
        Workout workout3 = new Workout(3, "2024-12-20", 102, "Comentario 3", 9);
        Workout workout4 = new Workout(4, "2025-01-01", 103, "Comentario 4", 12);
        Workout workout5 = new Workout(5, "2025-01-05", 104, "Comentario 5", 15);
        Workout workout6 = new Workout(6, "2025-01-16", 105, "Comentario 6", 18);
        Workout workout7 = new Workout(7, "2025-02-06", 106, "Comentario 7", 21);
        Workout workout8 = new Workout(8, "2025-02-19", 107, "Comentario 8", 24);
        Workout workout9 = new Workout(9, "2025-02-25", 108, "Comentario 9", 27);
        Workout workout10 = new Workout(10, "2025-02-27", 109, "Comentario 10", 30);
        
        workouts.add(workout1);
        workouts.add(workout2);
        workouts.add(workout3);
        workouts.add(workout4);
        workouts.add(workout5);
        workouts.add(workout6);
        workouts.add(workout7);
        workouts.add(workout8);
        workouts.add(workout9);
        workouts.add(workout10);
        
        calendar1.setWorkouts(workouts);
        
        calendar1.addActiveButtonListener(new ActiveButtonListener(){
            @Override
            public void activeButton(ArrayList<Workout> workouts) {
                String workoutInfo = "";
                for (Workout w: workouts) {
                    workoutInfo += "id usuario: " + w.getIdUsuari() + " workout comment: " + w.getComments() +
                            " number of exercises associated: " + w.getNumeroEjercicios() + "\n";
                }
                jTextField1.setText(workoutInfo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendar1 = new net.calendar.Calendar();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(calendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkoutCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.calendar.Calendar calendar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
